using System.Text.Json;
using ApplicationLayer;
using CoreModels;
using DataAccessLayer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace AzureGuard.Controllers;
[ApiController]
[Authorize]
[Route("api/projects/{projectId:long}/releases")]
public class ReleasesController(AppDbContext db, ReleaseService service, JenkinsService jenkins) : ControllerBase
{
    [HttpGet] public async Task<IActionResult> List(long projectId) => Ok(await db.Releases.Where(x => x.ProjectId == projectId).OrderByDescending(x => x.CreatedAt).ToListAsync());
    [HttpGet("{id:long}")] public async Task<IActionResult> Get(long projectId, long id) { var x = await db.Releases.SingleOrDefaultAsync(x => x.Id == id && x.ProjectId == projectId); return x is null ? NotFound() : Ok(x); }
    [HttpPost] public async Task<IActionResult> Create(long projectId, CreateReleaseRequest r) { if (!await db.Projects.AnyAsync(x => x.Id == projectId && x.IsActive)) return NotFound("Project not found."); if (string.IsNullOrWhiteSpace(r.ReleaseVersion) || r.ReleaseVersion.Length > 80) return BadRequest("Release version is required and must be at most 80 characters."); var x = new Release { ProjectId = projectId, ReleaseVersion = r.ReleaseVersion.Trim(), CommitSha = r.CommitSha, BranchName = string.IsNullOrWhiteSpace(r.BranchName) ? "main" : r.BranchName.Trim(), TriggeredByUserId = User.GetUserId() }; db.Releases.Add(x); await db.SaveChangesAsync(); db.AuditLogs.Add(new AuditLog { UserId = User.GetUserId(), ProjectId = projectId, ReleaseId = x.Id, Action = "RELEASE_CREATED" }); await db.SaveChangesAsync(); return CreatedAtAction(nameof(Get), new { projectId, id = x.Id }, x); }
    [HttpPost("{id:long}/pipeline")] public async Task<IActionResult> TriggerPipeline(long projectId, long id, CancellationToken cancellationToken) { var release = await db.Releases.SingleOrDefaultAsync(x => x.Id == id && x.ProjectId == projectId, cancellationToken); if (release is null) return NotFound(); var project = await db.Projects.FindAsync([projectId], cancellationToken); if (project is null) return NotFound(); try { return Ok(await jenkins.TriggerAsync(project, release, cancellationToken)); } catch (InvalidOperationException e) { return Problem(e.Message, statusCode: 503); } catch (HttpRequestException e) { return Problem($"Jenkins request failed: {e.Message}", statusCode: 502); } }
    [AllowAnonymous][HttpPost("{id:long}/pipeline/webhook")] public async Task<IActionResult> PipelineWebhook(long projectId, long id, JenkinsWebhookRequest r, [FromHeader(Name = "X-AzureGuard-Webhook-Secret")] string? secret) { if (string.IsNullOrWhiteSpace(secret) || !string.Equals(secret, HttpContext.RequestServices.GetRequiredService<Microsoft.Extensions.Options.IOptions<JenkinsOptions>>().Value.WebhookSecret, StringComparison.Ordinal)) return Unauthorized(); if (!await db.Releases.AnyAsync(x => x.Id == id && x.ProjectId == projectId)) return NotFound(); return await jenkins.UpdateFromWebhookAsync(id, r) ? Ok() : NotFound("No pipeline run exists for this release."); }
    [HttpPost("{id:long}/scans")] public async Task<IActionResult> Scan(long projectId, long id, IngestScanRequest r) { if (!await db.Releases.AnyAsync(x => x.Id == id && x.ProjectId == projectId)) return NotFound(); try { return Ok(await service.Ingest(id, r, User.GetUserId())); } catch (ArgumentException e) { return BadRequest(e.Message); } catch (InvalidOperationException e) { return Conflict(e.Message); } }
    [HttpPost("{id:long}/reports")] public async Task<IActionResult> Report(long projectId, long id, ScanReportRequest r) { if (!await db.Releases.AnyAsync(x => x.Id == id && x.ProjectId == projectId)) return NotFound(); try { return Ok(await service.IngestReport(id, r, User.GetUserId())); } catch (ArgumentException e) { return BadRequest(e.Message); } catch (JsonException e) { return BadRequest($"Invalid scanner report: {e.Message}"); } }
    [Authorize(Roles = "Reviewer,Admin")][HttpPost("{id:long}/approve")] public async Task<IActionResult> Approve(long projectId, long id) => await Decide(projectId, id, Statuses.Approved, "Release approved by reviewer.");
    [Authorize(Roles = "Reviewer,Admin")][HttpPost("{id:long}/reject")] public async Task<IActionResult> Reject(long projectId, long id) => await Decide(projectId, id, Statuses.Blocked, "Release rejected by reviewer.");
    [HttpPost("{id:long}/deploy")] public async Task<IActionResult> Deploy(long projectId, long id) { var release = await db.Releases.SingleOrDefaultAsync(x => x.Id == id && x.ProjectId == projectId); if (release is null) return NotFound(); if (release.Status != Statuses.Approved) return StatusCode(StatusCodes.Status403Forbidden, "Deployment is allowed only for approved releases."); return Accepted(new { releaseId = id, status = "DEPLOYMENT_QUEUED", message = "Release passed the AzureGuard deployment gate." }); }
    private async Task<IActionResult> Decide(long projectId, long id, string status, string reason) { var release = await db.Releases.SingleOrDefaultAsync(x => x.Id == id && x.ProjectId == projectId); if (release is null) return NotFound(); if (release.Status != Statuses.ManualReview) return Conflict("Only releases awaiting manual review can be decided."); release.Status = status; release.CompletedAt = DateTime.UtcNow; db.PolicyDecisions.Add(new PolicyDecision { ReleaseId = id, RiskScore = await db.RiskScores.Where(x => x.ReleaseId == id).Select(x => (decimal?)x.Score).FirstOrDefaultAsync() ?? 0, Decision = status, DecisionReason = reason, DecidedBy = User.Identity?.Name ?? "REVIEWER" }); db.AuditLogs.Add(new AuditLog { UserId = User.GetUserId(), ProjectId = projectId, ReleaseId = id, Action = status == Statuses.Approved ? "RELEASE_APPROVED" : "RELEASE_REJECTED" }); await db.SaveChangesAsync(); return Ok(release); }
    [HttpGet("{id:long}/dashboard")] public async Task<IActionResult> Dashboard(long projectId, long id) { var r = await db.Releases.SingleOrDefaultAsync(x => x.Id == id && x.ProjectId == projectId); if (r is null) return NotFound(); return Ok(new { release = r, scans = await db.ScanResults.Where(x => x.ReleaseId == id).ToListAsync(), pipelineRuns = await db.PipelineRuns.Where(x => x.ReleaseId == id).OrderByDescending(x => x.CreatedAt).ToListAsync(), risk = await db.RiskScores.Where(x => x.ReleaseId == id).OrderByDescending(x => x.CreatedAt).FirstOrDefaultAsync(), decision = await db.PolicyDecisions.Where(x => x.ReleaseId == id).OrderByDescending(x => x.DecidedAt).FirstOrDefaultAsync() }); }
}
