using System.Text.Json;
using System.Xml.Linq;
using CoreModels;
namespace ApplicationLayer;
public sealed class ScannerReportParser
{
    public IngestScanRequest Parse(ScanReportRequest request) { var type=request.ScanType.Trim().ToUpperInvariant(); var tool=request.ToolName.Trim().ToUpperInvariant(); if (tool is "GITLEAKS" or "TRIVY" or "CHECKOV" or "SONARQUBE") return ParseJson(type,tool,request.Status,request.Report); if (tool is "JUNIT" or "DOTNET_TEST" or "TEST") return ParseJUnit(type,tool,request.Status,request.Report); throw new ArgumentException($"Unsupported scanner report: {request.ToolName}."); }
    private static IngestScanRequest ParseJson(string type,string tool,string status,string raw) { using var doc=JsonDocument.Parse(raw); var fs=new List<FindingRequest>(); if(tool=="GITLEAKS") foreach(var x in doc.RootElement.EnumerateArray()) fs.Add(new(type,"CRITICAL",Get(x,"RuleID"),Get(x,"Description"),"Potential secret detected",Get(x,"File"),GetInt(x,"StartLine"),Get(x,"Fingerprint"))); if(tool=="TRIVY"&&doc.RootElement.TryGetProperty("Results",out var rs)) foreach(var result in rs.EnumerateArray()) if(result.TryGetProperty("Vulnerabilities",out var vs)) foreach(var x in vs.EnumerateArray()) fs.Add(new(type,Map(Get(x,"Severity")),Get(x,"VulnerabilityID"),Get(x,"Title"),Get(x,"Description"),Get(result,"Target"),null,Get(x,"PrimaryURL"))); if(tool=="CHECKOV"&&doc.RootElement.TryGetProperty("results",out var cr)&&cr.TryGetProperty("failed_checks",out var failed)) foreach(var x in failed.EnumerateArray()) fs.Add(new(type,Map(Get(x,"severity")),Get(x,"check_id"),Get(x,"check_name"),Get(x,"check_name"),Get(x,"file_path"),GetInt(x,"file_line_range"),Get(x,"guideline"))); if(tool=="SONARQUBE"&&doc.RootElement.TryGetProperty("issues",out var issues)) foreach(var x in issues.EnumerateArray()) fs.Add(new(type,Map(Get(x,"severity")),Get(x,"rule"),Get(x,"message"),Get(x,"message"),Get(x,"component"),GetInt(x,"line"),null)); return Build(type,tool,status,raw,fs); }
    private static IngestScanRequest ParseJUnit(string type,string tool,string status,string raw) { var root=XDocument.Parse(raw).Root; var fs=root?.Descendants("failure").Select(x=>new FindingRequest(type,"HIGH",null,"Test failure",x.Value,x.Parent?.Attribute("classname")?.Value,null,null)).ToList()??[]; return Build(type,tool,status,raw,fs); }
    private static IngestScanRequest Build(string type,string tool,string status,string raw,List<FindingRequest> fs)=>new(type,tool,status,fs.Count(x=>x.Severity=="CRITICAL"),fs.Count(x=>x.Severity=="HIGH"),fs.Count(x=>x.Severity=="MEDIUM"),fs.Count(x=>x.Severity=="LOW"),fs.Count(x=>x.Severity=="INFO"),raw,null,fs);
    private static string Map(string? value)=>value?.ToUpperInvariant() switch {"BLOCKER" or "CRITICAL"=>"CRITICAL","HIGH" or "MAJOR"=>"HIGH","MEDIUM" or "MODERATE" or "MINOR"=>"MEDIUM","LOW"=>"LOW",_=>"INFO"}; private static string? Get(JsonElement x,string n)=>x.TryGetProperty(n,out var v)?v.ValueKind==JsonValueKind.String?v.GetString():v.ToString():null; private static int? GetInt(JsonElement x,string n){if(!x.TryGetProperty(n,out var v))return null;if(v.ValueKind==JsonValueKind.Number&&v.TryGetInt32(out var n1))return n1;if(v.ValueKind==JsonValueKind.Array&&v.GetArrayLength()>0&&v[0].TryGetInt32(out n1))return n1;return null;}
}
