using System.ComponentModel.DataAnnotations;
namespace CoreModels;
public static class Statuses { public const string Created = "CREATED", Approved = "APPROVED", ManualReview = "MANUAL_REVIEW", Blocked = "BLOCKED", PipelineRunning = "PIPELINE_RUNNING", Scanning = "SCANNING", Failed = "FAILED"; }
public class AppUser { public long Id { get; set; } public string FullName { get; set; } = ""; public string Email { get; set; } = ""; public string RoleName { get; set; } = "Developer"; public bool IsActive { get; set; } = true; public string PasswordHash { get; set; } = ""; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class Project { public long Id { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public string RepositoryUrl { get; set; } = ""; public string BranchName { get; set; } = "main"; public string TechStack { get; set; } = "OTHER"; public string? BuildCommand { get; set; } public string? TestCommand { get; set; } public string DockerfilePath { get; set; } = "./Dockerfile"; public string? HelmChartPath { get; set; } public bool IsActive { get; set; } = true; public long? CreatedByUserId { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class Release { public long Id { get; set; } public long ProjectId { get; set; } public string ReleaseVersion { get; set; } = ""; public string? CommitSha { get; set; } public string BranchName { get; set; } = "main"; public long? TriggeredByUserId { get; set; } public string Status { get; set; } = Statuses.Created; public DateTime? StartedAt { get; set; } public DateTime? CompletedAt { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class ScanResult { public long Id { get; set; } public long ReleaseId { get; set; } public string ScanType { get; set; } = ""; public string ToolName { get; set; } = ""; public string Status { get; set; } = "PASSED"; public int CriticalCount { get; set; } public int HighCount { get; set; } public int MediumCount { get; set; } public int LowCount { get; set; } public int InfoCount { get; set; } public string? RawSummaryJson { get; set; } public string? ReportUrl { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class RiskScore { public long Id { get; set; } public long ReleaseId { get; set; } public string ModelName { get; set; } = "RULE_BASED_V1"; public decimal Score { get; set; } public string RiskLevel { get; set; } = "LOW"; public string? FeatureJson { get; set; } public string? PredictionReason { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class PolicyDecision { public long Id { get; set; } public long ReleaseId { get; set; } public decimal RiskScore { get; set; } public string Decision { get; set; } = "APPROVED"; public string DecisionReason { get; set; } = ""; public string DecidedBy { get; set; } = "SYSTEM"; public DateTime DecidedAt { get; set; } = DateTime.UtcNow; }
public class PipelineRun { public long Id { get; set; } public long ReleaseId { get; set; } public string Provider { get; set; } = "JENKINS"; public string? ExternalRunId { get; set; } public string? PipelineUrl { get; set; } public string Status { get; set; } = "QUEUED"; public DateTime? StartedAt { get; set; } public DateTime? CompletedAt { get; set; } public string? ErrorMessage { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class ScanFinding { public long Id { get; set; } public long ReleaseId { get; set; } public long? ScanResultId { get; set; } public ScanResult? ScanResult { get; set; } public string ScanType { get; set; } = ""; public string Severity { get; set; } = "INFO"; public string? RuleId { get; set; } public string? Title { get; set; } public string? Description { get; set; } public string? FilePath { get; set; } public int? LineNumber { get; set; } public string? Fingerprint { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class Policy { public long Id { get; set; } public long ProjectId { get; set; } public string Name { get; set; } = "Default"; public bool IsActive { get; set; } = true; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class PolicyRule { public long Id { get; set; } public long PolicyId { get; set; } public string RuleCode { get; set; } = ""; public string Description { get; set; } = ""; public bool IsActive { get; set; } = true; public decimal Threshold { get; set; } public string Action { get; set; } = Statuses.ManualReview; }
public class AuditLog { public long Id { get; set; } public long? UserId { get; set; } public long? ProjectId { get; set; } public long? ReleaseId { get; set; } public string Action { get; set; } = ""; public string? DetailsJson { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public record SignupRequest(string FullName, string Email, string Password, string? RoleName); public record LoginRequest(string Email, string Password); public record AuthResponse(long UserId, string FullName, string Email, string RoleName, string Token); public record CreateProjectRequest(string Name, string? Description, string RepositoryUrl, string? BranchName, string? TechStack, string? BuildCommand, string? TestCommand, string? DockerfilePath, string? HelmChartPath); public record CreateReleaseRequest(string ReleaseVersion, string? CommitSha, string? BranchName); public record FindingRequest(string ScanType, string Severity, string? RuleId, string? Title, string? Description, string? FilePath, int? LineNumber, string? Fingerprint); public record IngestScanRequest(string ScanType, string ToolName, string Status, int CriticalCount, int HighCount, int MediumCount, int LowCount, int InfoCount, string? RawSummaryJson, string? ReportUrl, IReadOnlyList<FindingRequest>? Findings); public record ScanReportRequest(string ScanType, string ToolName, string Status, string Report); public record DecisionResponse(long ReleaseId, decimal RiskScore, string RiskLevel, string Decision, string Reason); public record JenkinsWebhookRequest(string ExternalRunId, string Status, string? PipelineUrl, string? ErrorMessage);
